all: anel

anel: anel.o smpl.o rand.o
	$(LINK.c) -o $@ -Bstatic anel.o smpl.o rand.o -lm

smpl.o: smpl.c smpl.h
	$(COMPILE.c)  -g smpl.c

anel.o: anel.c smpl.h
	$(COMPILE.c) -g  anel.c

rand.o: rand.c
	$(COMPILE.c) -g rand.c

clean:
	$(RM) *.o anel relat saida
